Functions to upgrade the last node in environment
If number of OSD nodes is less then replication factor of the Ceph cluster, Fuel
by default won't let to delete another node to avoid data loss.
These functions delete node with --delete-from-db key. They assume that the
deployment information is updated in Nailgun DB directly.

diff --git a/octane/bin/functions b/octane/bin/functions
--- a/octane/bin/functions
+++ b/octane/bin/functions
@@ -566,6 +566,63 @@ assign_node_to_env(){
     NODE_ID=$id
 }
 
+nodes_disks_equal() {
+    set -e
+    [ -z "$2" ] && die "IDs of 2 nodes required but not provided, exiting"
+    [ -f "${FUEL_CACHE}/node_$1/disks.yaml" ]
+    [ -f "${FUEL_CACHE}/node_$2/disks.yaml" ]
+    python -c "import yaml; import sys;
+disks1 = yaml.load(open('"$FUEL_CACHE"/node_$1/disks.yaml'));
+disks2 = yaml.load(open('"$FUEL_CACHE"/node_$2/disks.yaml'));
+for disk in disks1:
+    if disk['extra'] in [d['extra'] for d in disks2]:
+        continue;
+    else:
+        sys.exit(1)"
+    return $?
+}
+
+assign_last_node_to_env(){
+    local orig_id
+    local roles
+    local mac
+    local host
+    local id
+    local last_node
+    [ -z "$1" ] && die "No node ID provided, exiting"
+    [ -z "$2" ] && die "No seed env ID provided, exiting"
+    roles=$(fuel node --node $1 \
+        | awk -F\| '/^'$1'/ {gsub(" ", "", $7);print $7}')
+    orig_id=$(get_env_by_node $1)
+    host=$(get_host_ip_by_node_id $1)
+    fuel node --node $1 --env $orig_id --delete-from-db
+    dockerctl shell cobbler cobbler system remove --name node-$1
+    ssh root@node-$1 shutdown -r now
+    last_node=$(get_last_node)
+    while :
+        do
+            id=$(get_last_node)
+            get_node_settings $id
+            [[ $id > $last_node ]] &&
+            nodes_disks_equal $1 $id && {
+                echo "Found node $id, adding node to env $2 as $roles"
+                break
+            }
+            sleep 30
+        done
+    fuel node --node $id --env $2 set --role ${roles:-compute,ceph-osd}
+    [ -f "interfaces.fixture.yaml" ] || die "No interfaces fixture provided, exiting"
+    apply_network_settings $id
+    fuel node --node $id --disk --download
+    ./copy-node-settings disks ${FUEL_CACHE}/node_$id/disks.yaml \
+        ${FUEL_CACHE}/node_$1/disks.yaml by_extra > /tmp/node-$id-disks.yaml
+    cp /tmp/node-$id-disks.yaml ${FUEL_CACHE}/node_$id/disks.yaml
+    ./keep-ceph-partition ${FUEL_CACHE}/node_$id/disks.yaml > /tmp/disks-ceph-partition.yaml
+    mv /tmp/disks-ceph-partition.yaml ${FUEL_CACHE}/node_$id/disks.yaml
+    upload_node_settings $id
+    NODE_ID=$id
+}
+
 prepare_ceph_osd_upgrade() {
     local seed_id
     local nodes
@@ -675,6 +732,47 @@ upgrade_node() {
             replace_ip_addresses $1 $1 $br_name $discard_ips
             replace_vip_address $1 $1 $br_name $filename
         done
+    remove_predefined_networks $1
+    upload_deployment_info $1
+    fuel node --env $1 --node $NODE_ID --deploy
+    wait_for_node $NODE_ID "ready"
+}
+
+upgrade_last_node() {
+    local roles
+    local role
+    local id
+    local filename
+    local discard_ips
+    [ -z "$1" ] && die "No 6.0 env and node ID provided, exiting"
+    [ -z "$2" ] && die "No node ID provided, exiting"
+    roles=$(fuel node --node $2 \
+        | awk -F\| '/^'$2'/ {gsub(" ", "", $7);print $7}' \
+        | sed -re 's%,% %')
+    for role in $roles
+        do
+            case $role in
+                compute)
+                    prepare_compute_upgrade "$@"
+                    ;;
+                ceph-osd)
+                    prepare_osd_node_upgrade $2
+                    set_osd_noout $1
+                    ;;
+                *)
+                    echo "Role $role unsupported, skipping"
+                    ;;
+             esac
+         done
+    assign_last_node_to_env $2 $1 # Set NODE_ID global var to the ID of reassigned node
+    [ $NODE_ID == 0 ] && die "Cannot determine ID of reassigned node, exiting"
+    fuel node --env $1 --node $NODE_ID --provision
+    wait_for_node $NODE_ID "provisioned"
+    get_deployment_info $1 download
+    rmdir ${FUEL_CACHE}/deployment_$1.download
+    mv ${FUEL_CACHE}/deployment_$1 ${FUEL_CACHE}/deployment_$1.download
+    get_deployment_info $1
+    mv ${FUEL_CACHE}/deployment_$1.download/* ${FUEL_CACHE}/deployment_$1/
     remove_predefined_networks $1
     upload_deployment_info $1
     fuel node --env $1 --node $NODE_ID --deploy
