Store deployment and node settings in cache dir

diff --git a/octane/bin/functions b/octane/bin/functions
--- a/octane/bin/functions
+++ b/octane/bin/functions
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 NODE_ID=0
+FUEL_CACHE="/tmp/octane/deployment"
 
 die() {
     echo "$1"
@@ -53,9 +54,10 @@ get_deployment_info() {
 # Download deployment config from Fuel master for environment ENV to subdir in
 # current directory.
     [ -z "$1" ] && die "No environment ID provided, exiting"
-    [ -d "./deployment_$1" ] && rm -r ./deployment_$1
+    [ -d "$FUEL_CACHE" ] || mkdir -p "$FUEL_CACHE"
+    [ -d "${FUEL_CACHE}/deployment_$1" ] && rm -r ${FUEL_CACHE}/deployment_$1
     cmd=${2:-default}
-    fuel --env $1 deployment --$cmd
+    fuel --env $1 deployment --$cmd --dir ${FUEL_CACHE}
 }
 
 get_ips_from_deploy_info() {
@@ -66,9 +68,9 @@ get_ips_from_deploy_info() {
     local primary_cic
     [ -z "$1" ] && die "No environment ID and bridge name provided, exiting"
     [ -z "$2" ] && die "No bridge name provided, exiting"
-    primary_cic=$(basename ./deployment_$1/primary-controller_*.yaml)
+    primary_cic=$(basename ${FUEL_CACHE}/deployment_$1/primary-controller_*.yaml)
     filename=${3:-$primary_cic}
-    echo $(python ./extract-cic-ips ./deployment_$1/$filename $2)
+    echo $(python ./extract-cic-ips ${FUEL_CACHE}/deployment_$1/$filename $2)
 }
 
 get_vip_from_deploy_info() {
@@ -82,10 +84,10 @@ get_vip_from_deploy_info() {
         | awk '/br-ex/ {print "public_vip:"} \
         /br-mgmt/ {print "management_vip:"}')
     [ -z "$br_name" ] && die "No bridge name provided, exiting"
-    primary_cic=$(basename ./deployment_$1/primary-controller_*.yaml)
+    primary_cic=$(basename ${FUEL_CACHE}/deployment_$1/primary-controller_*.yaml)
     filename=${3:-$primary_cic}
-    [ -z "$filename" ] && filename=$(ls ./deployment_$1 | head -1)
-    [ -n "$br_name" ] && echo $(grep $br_name ./deployment_$1/$filename \
+    [ -z "$filename" ] && filename=$(ls ${FUEL_CACHE}/deployment_$1 | head -1)
+    [ -n "$br_name" ] && echo $(grep $br_name ${FUEL_CACHE}/deployment_$1/$filename \
         | awk '{print $2}')
 }
 
@@ -94,15 +96,16 @@ get_primary_ip() {
     local primary_id
     [ -z "$1" ] && die "No environment ID and bridge name provided, exiting"
     [ -z "$2" ] && die "No bridge name provided, exiting"
-    filename=$(basename ./deployment_$1/primary-controller_*.yaml)
-    echo $(python ./extract-primary-ip "./deployment_$1/$filename" $2)
+    filename=$(basename ${FUEL_CACHE}/deployment_$1/primary-controller_*.yaml)
+    echo $(python ./extract-primary-ip "${FUEL_CACHE}/deployment_$1/$filename" $2)
 }
 
 upload_deployment_info() {
 # Upload deployment configration with modifications to Fuel master for
 # environment ENV.
     [ -z "$1" ] && die "No environment ID provided, exiting"
-    [ -d "./deployment_$1" ] && fuel --env $1 deployment --upload
+    [ -d "$FUEL_CACHE" ] &&
+    fuel --env $1 deployment --upload --dir $FUEL_CACHE
 }
 
 replace_ip_addresses() {
@@ -115,7 +118,7 @@ replace_ip_addresses() {
     [ -z "$1" ] && die "No orig, seed env IDs, bridge name and IP addresses provided, exiting"
     [ -z "$2" ] && die "No seed env ID, bridge name and IP addresses provided, exiting"
     [ -z "$3" ] && die "No bridge name and IP addresses provided, exiting"
-    dirname="./deployment_$2"
+    dirname="${FUEL_CACHE}/deployment_$2"
     tmpfile="/tmp/env-$1-cic-$3-ips"
     shift 3
     for orig_ip in $(cat "$tmpfile")
@@ -135,7 +138,7 @@ replace_vip_address() {
     local seed_vip
     local dirname
     local br_name
-    dirname=./deployment_$2
+    dirname="${FUEL_CACHE}/deployment_$2"
     br_name=$3
     orig_vip=$(get_vip_from_cics $1 $br_name)
     [ -z "$orig_vip" ] && die "Cannot find VIP on $br_name in 5.1 env, exiting"
@@ -161,9 +164,9 @@ replace_seed_ips() {
 
 backup_deployment_info() {
     [ -z "$1" ] && die "No env ID provided, exiting"
-    [ -d "deployment_$1" ] && {
-        [ -d "deployment_$1.orig" ] || mkdir "deployment_$1.orig"
-        cp -R deployment_$1/*.yaml deployment_$1.orig/
+    [ -d "${FUEL_CACHE}/deployment_$1" ] && {
+        [ -d "${FUEL_CACHE}/deployment_$1.orig" ] || mkdir "${FUEL_CACHE}/deployment_$1.orig"
+        cp -R ${FUEL_CACHE}/deployment_$1/*.yaml ${FUEL_CACHE}/deployment_$1.orig/
     }
 }
 
@@ -172,13 +175,13 @@ remove_patch_transformations() {
 # controllers from original environment while physically connected to the same
 # L2 segment.
     [ -z "$1" ] && die "No env ID provided, exiting"
-    python ../helpers/transformations.py deployment_$1 remove_patch_ports
+    python ../helpers/transformations.py ${FUEL_CACHE}/deployment_$1 remove_patch_ports
 }
 
 disable_ping_checker() {
     [ -z "$1" ] && die "No env ID provided, exiting"
-    [ -d "./deployment_$1" ] || die "Deployment info directory not found, exiting"
-    ls deployment_$1/** | xargs -I@ sh -c "echo 'run_ping_checker: \"false\"' >> @"
+    [ -d "${FUEL_CACHE}/deployment_$1" ] || die "Deployment info directory not found, exiting"
+    ls ${FUEL_CACHE}/deployment_$1/** | xargs -I@ sh -c "echo 'run_ping_checker: \"false\"' >> @"
 }
 
 prepare_seed_deployment_info() {
@@ -195,23 +198,25 @@ prepare_seed_deployment_info() {
 
 remove_predefined_networks() {
     [ -z "$1" ] && die "No env ID provided, exiting"
-    python ../helpers/transformations.py deployment_$1 remove_predefined_nets
+    python ../helpers/transformations.py ${FUEL_CACHE}/deployment_$1 remove_predefined_nets
 }
 
 prepare_cic_disk_fixture() {
     local node_id
     [ -z "$1" ] && die "No env ID provided, exiting"
     node_id=$(fuel node --env $1 | awk '/'${2:-controller}'/{print($1)}' | head -1)
-    fuel node --node $node_id --disk --download
-    [ -f "node_$node_id/disks.yaml" ] && cp node_$node_id/disks.yaml ./disks.fixture.yaml
+    fuel node --node $node_id --disk --download --dir $FUEL_CACHE
+    [ -f "${FUEL_CACHE}/node_$node_id/disks.yaml" ] &&
+    cp ${FUEL_CACHE}/node_$node_id/disks.yaml ./disks.fixture.yaml
 }
 
 prepare_cic_network_fixture() {
     local node_id
     [ -z "$1" ] && die "No env ID provided, exiting"
     node_id=$(fuel node --env $1 | awk '/'${2:-controller}'/{print($1)}' | head -1)
-    fuel node --node $node_id --network --download
-    [ -f "node_$node_id/interfaces.yaml" ] && cp node_$node_id/interfaces.yaml ./interfaces.fixture.yaml
+    fuel node --node $node_id --network --download --dir $FUEL_CACHE
+    [ -f "${FUEL_CACHE}/node_$node_id/interfaces.yaml" ] &&
+    cp ${FUEL_CACHE}/node_$node_id/interfaces.yaml ./interfaces.fixture.yaml
 }
 
 list_nodes() {
@@ -415,14 +420,14 @@ create_patch_ports() {
     local node
     local node_id
     local filename
-    [ -d ./deployment_$1.orig ] || die "Deployment information not found for env $1, exiting"
+    [ -d ${FUEL_CACHE}/deployment_$1.orig ] || die "Deployment information not found for env $1, exiting"
     [ -z "$1" ] && die "No env ID provided, exiting"
     br_name=$2
     nodes=$(list_nodes $1 'controller')
     for node in $nodes
         do
             node_id=$(echo $node | awk -F"-" '{print $2}')
-            filename=$(ls deployment_$1.orig/*_$node_id.yaml | head -1)
+            filename=$(ls ${FUEL_CACHE}/deployment_$1.orig/*_$node_id.yaml | head -1)
             ./create-patch-ports $filename $br_name \
                 | xargs -I {} ssh root@$node {}
         done
@@ -451,36 +456,37 @@ delete_patch_ports() {
 apply_disk_settings() {
     local disk_file
     [ -z "$1" ] && die "No node ID provided, exiting"
-    disk_file="./node_$1/disks.yaml"
-    fuel node --node $1 --disk --download
+    disk_file="${FUEL_CACHE}/node_$1/disks.yaml"
+    fuel node --node $1 --disk --download --dir $FUEL_CACHE
     ./copy-node-settings disks $disk_file ./disks.fixture.yaml by_name \
         > /tmp/disks_$1.yaml
     mv /tmp/disks_$1.yaml $disk_file
-    fuel node --node $1 --disk --upload
+    fuel node --node $1 --disk --upload --dir $FUEL_CACHE
 }
 
 apply_network_settings() {
     local iface_file
     [ -z "$1" ] && die "No node ID provided, exiting"
-    iface_file="./node_$1/interfaces.yaml"
-    fuel node --node $1 --network --download
+    iface_file="${FUEL_CACHE}/node_$1/interfaces.yaml"
+    fuel node --node $1 --network --download --dir $FUEL_CACHE
     ./copy-node-settings interfaces $iface_file \
         ./interfaces.fixture.yaml > /tmp/interfaces_$1.yaml
     mv /tmp/interfaces_$1.yaml $iface_file
-    fuel node --node $1 --network --upload
+    fuel node --node $1 --network --upload --dir $FUEL_CACHE
 }
 
 get_node_settings() {
     [ -z "$1" ] && die "No node ID provided, exiting"
-    fuel node --node $1 --network --download
-    fuel node --node $1 --disk --download
+    [ -d "$FUEL_NODE" ] || mkdir -p "$FUEL_CACHE"
+    fuel node --node $1 --network --download --dir $FUEL_CACHE
+    fuel node --node $1 --disk --download --dir $FUEL_CACHE
 }
 
 upload_node_settings() {
     [ -z "$1" ] && die "No node ID provided, exiting"
-    [ -d "./node_$1" ] || die "Local node settings not found, exiting"
-    fuel node --node $1 --network --upload
-    fuel node --node $1 --disk --upload
+    [ -d "${FUEL_CACHE}/node_$1" ] || die "Local node settings not found, exiting"
+    fuel node --node $1 --network --upload --dir $FUEL_CACHE
+    fuel node --node $1 --disk --upload --dir $FUEL_CACHE
 }
 
 get_env_by_node() {
@@ -536,16 +542,16 @@ assign_node_to_env(){
     apply_network_settings $id
     if [ $id -ne $1 ]
         then
-            fuel node --node $id --disk --download
-            ./copy-node-settings disks node_$id/disks.yaml \
-                node_$1/disks.yaml by_extra > /tmp/node-$id-disks.yaml
-            cp /tmp/node-$id-disks.yaml node_$id/disks.yaml
+            fuel node --node $id --disk --download --dir $FUEL_CACHE
+            ./copy-node-settings disks ${FUEL_CACHE}/node_$id/disks.yaml \
+                ${FUEL_CACHE}/node_$1/disks.yaml by_extra > /tmp/node-$id-disks.yaml
+            cp /tmp/node-$id-disks.yaml ${FUEL_CACHE}/node_$id/disks.yaml
         else
             [ -f "disks.fixture.yaml" ] || die "No disks fixture provided, exiting"
             apply_disk_settings $id
         fi
-    ./keep-ceph-partition node_$id/disks.yaml > /tmp/disks-ceph-partition.yaml
-    mv /tmp/disks-ceph-partition.yaml node_$id/disks.yaml
+    ./keep-ceph-partition ${FUEL_CACHE}/node_$id/disks.yaml > /tmp/disks-ceph-partition.yaml
+    mv /tmp/disks-ceph-partition.yaml ${FUEL_CACHE}/node_$id/disks.yaml
     upload_node_settings $id
     NODE_ID=$id
 }
@@ -647,9 +653,10 @@ upgrade_node() {
     fuel node --env $1 --node $NODE_ID --provision
     wait_for_node $NODE_ID "provisioned"
     get_deployment_info $1 download
-    rmdir ./deployment_$1.download && mv ./deployment_$1 ./deployment_$1.download
+    rmdir ${FUEL_CACHE}/deployment_$1.download
+    mv ${FUEL_CACHE}/deployment_$1 ${FUEL_CACHE}/deployment_$1.download
     get_deployment_info $1
-    mv ./deployment_$1.download/* ./deployment_$1/
+    mv ${FUEL_CACHE}/deployment_$1.download/* ${FUEL_CACHE}/deployment_$1/
     for br_name in br-ex br-mgmt
         do
             get_ips_from_cics $1 $br_name > "/tmp/env-$1-cic-$br_name-ips"
